export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_LIBRARIES_SUCCESS = 'LOAD_LIBRARIES_SUCCESS'
export const LOAD_LIBRARIES_FAILURE = 'LOAD_LIBRARIES_FAILURE'

export const ADD_DATA = 'ADD_DATA'
export const ADD_LIBRARIES_SUCCESS = 'ADD_LIBRARIES_SUCCESS'
export const ADD_LIBRARIES_FAILURE = 'ADD_LIBRARIES_FAILURE'

export const EDIT_DATA = 'EDIT_DATA'
export const EDIT_LIBRARIES_SUCCESS = 'EDIT_LIBRARIES_SUCCESS'
export const EDIT_LIBRARIES_FAILURE = 'EDIT_LIBRARIES_FAILURE'

export const DELETE_DATA = 'DELETE_DATA'
export const DELETE_LIBRARIES_SUCCESS = 'DELETE_LIBRARIES_SUCCESS'
export const DELETE_LIBRARIES_FAILURE = 'DELETE_LIBRARIES_FAILURE'

export const ADD_DATALOAN = 'ADD_DATALOAN'
export const ADD_LOANBOOK_SUCCESS = 'ADD_LOANBOOK_SUCCESS'
export const ADD_LOANBOOK_FAILURE = 'ADD_LOANBOOK_FAILURE'

export const EDIT_DATALOAN = 'EDIT_DATALOAN'
export const EDIT_LOANBOOK_SUCCESS = 'EDIT_LOANBOOK_SUCCESS'
export const EDIT_LOANBOOK_FAILURE = 'EDIT_LOANBOOK_FAILURE'

export const ADD_DATAUSER = 'ADD_DATAUSER'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE'