export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_LIBRARIES_SUCCESS = 'LOAD_LIBRARIES_SUCCESS'
export const LOAD_LIBRARIES_FAILURE = 'LOAD_LIBRARIES_FAILURE'

export const ADD_DATA = 'ADD_DATA'
export const ADD_LIBRARIES_SUCCESS = 'ADD_LIBRARIES_SUCCESS'
export const ADD_LIBRARIES_FAILURE = 'ADD_LIBRARIES_FAILURE'

export const EDIT_DATA = 'EDIT_DATA'
export const EDIT_LIBRARIES_SUCCESS = 'EDIT_LIBRARIES_SUCCESS'
export const EDIT_LIBRARIES_FAILURE = 'EDIT_LIBRARIES_FAILURE'

export const DELETE_DATA = 'DELETE_DATA'
export const DELETE_LIBRARIES_SUCCESS = 'DELETE_LIBRARIES_SUCCESS'
export const DELETE_LIBRARIES_FAILURE = 'DELETE_LIBRARIES_FAILURE'